# Generated by Django 3.2.5 on 2021-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(null='Ture', upload_to='news/attachments/'),
            preserve_default='Ture',
        ),
    ]
