# Generated by Django 3.2.5 on 2021-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0003_alter_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(null=True, upload_to='news/attachments/', verbose_name='附件'),
        ),
    ]
