# Generated by Django 3.2.5 on 2021-08-18 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0004_alter_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='內容'),
        ),
    ]
