# Generated by Django 3.2.5 on 2021-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0005_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
    ]
