# Generated by Django 3.2.5 on 2021-09-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0007_auto_20210906_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='收件人')),
            ],
        ),
    ]
